"""Define the intentionally supported package-level Python interface.

Focused implementations live in modules such as ``github_client.py``, ``github_tag.py``,
``dependency_analysis.py``, ``dependency_change.py``, ``ci_dependency_exercise.py``,
``packaging_method.py``, ``target_python_relevance.py``, ``upstream_interval.py``,
``upstream_interval_acquisition.py``, ``upstream_claim.py``, ``uv_lock_change.py``, and
``pypi_client.py``. Re-exporting selected contracts lets callers use stable
package-level imports without depending on file layout.

Importing ``upgradepilot`` performs no network request. Acquisition starts only when a
caller invokes a client method.
"""

from .ci_dependency_exercise import (
    DependencyCIExerciseResult,
    DependencyCIExerciseState,
    WorkflowDependencyExerciseInput,
    WorkflowDependencyExerciseResult,
    evaluate_dependency_ci_exercise,
)
from .dependency_analysis import (
    DependencyChangeAnalysis,
    DependencyChangeAnalysisResult,
    analyze_dependency_change,
    is_uv_lock_file,
)
from .dependency_change import (
    DEPENDENCY_CHANGE_PROBLEM_CODES,
    DependencyChangeComparisonResult,
    DependencyChangeEvidenceProblem,
    DependencyChangeExtractionResult,
    DependencyChangeProblemCode,
    DependencyChangeResult,
    DependencyEvidenceMethod,
    DependencyFileEvidence,
    DependencyFileFormat,
    DependencyVersionChange,
    ExtractedDependencyVersionChange,
    PinnedDependencyChange,
    UnsupportedDependencyChange,
    compare_extracted_dependency_changes,
    extract_pinned_dependency_change,
    normalize_package_name,
)
from .exact_requirement_change import (
    extract_exact_requirement_changes,
    is_admitted_requirements_file,
    is_exact_requirement_file,
)
from .github_client import (
    ChangedFile,
    GitHubAcquisitionError,
    GitHubReadClient,
    GitHubResponseError,
    PullRequestIdentity,
    UpgradePilotInputError,
)
from .github_release import (
    GitHubReleaseClient,
    GitHubReleaseEvidence,
    GitHubReleaseProblem,
    GitHubReleaseResult,
)
from .github_tag import (
    GitHubTagCommitClient,
    GitHubTagCommitEvidence,
    GitHubTagCommitProblem,
    GitHubTagCommitResult,
)
from .packaging_method import (
    OrderedCrossedReleaseVersions,
    PackagingVersionProblem,
    ParsedDependencyReleaseInterval,
    PythonLineSpecifierEvaluation,
    PythonLineSpecifierProblem,
    evaluate_python_line_specifier,
    order_crossed_release_versions,
    parse_dependency_release_interval,
)
from .pypi_client import (
    DistributionFile,
    PackageReleaseEvidence,
    PackageReleaseIndexEvidence,
    PackageReleaseIndexProblem,
    PackageReleaseIndexResult,
    PackageReleaseProblem,
    PackageReleaseResult,
    ProjectUrlCandidate,
    PyPIReleaseClient,
    PyPIReleaseIndexClient,
)
from .pypi_provenance import (
    FileProvenanceEvidence,
    FileProvenanceProblem,
    FileProvenanceResult,
    PublisherIdentity,
    PyPIProvenanceClient,
)
from .target_python_relevance import (
    TargetPythonRelevanceResult,
    TargetPythonRelevanceState,
    evaluate_target_python_relevance,
)
from .upstream_claim import (
    CandidateUpstreamClaim,
    CandidateUpstreamClaimResult,
    GroundedPythonSupportDropClaim,
    GroundedUpstreamClaimSource,
    UpstreamSupportDropClaimProblem,
    UpstreamSupportDropClaimResult,
    validate_support_drop_candidates,
)
from .upstream_interval import (
    UPSTREAM_SOURCE_AUTHORITY_ORDER,
    AuthoritativeUpstreamIntervalEvidence,
    CrossedReleaseIndexEvidence,
    DependencyReleaseInterval,
    IntervalGitHubReleaseSource,
    PackageMetadataCorroboration,
    TaggedChangelogEvidence,
    UpstreamAuthoritySourceProblem,
    UpstreamIntervalAuthorityProblem,
    UpstreamIntervalAuthorityResult,
    assemble_upstream_interval_authority,
    release_interval_from_dependency_change,
    upstream_source_role,
)
from .upstream_interval_acquisition import (
    CrossedReleaseIndexSelectionProblem,
    CrossedReleaseIndexSelectionResult,
    SelectedCrossedReleaseIndex,
    select_crossed_release_index,
)
from .upstream_source import (
    UpstreamReleaseEvidence,
    UpstreamSourceProblem,
    UpstreamSourceResolver,
    UpstreamSourceResult,
    normalize_project_url_label,
)
from .uv_lock_change import (
    extract_uv_lock_changes,
    is_modified_uv_lock_file,
)

__all__ = (
    "AuthoritativeUpstreamIntervalEvidence",
    "CandidateUpstreamClaim",
    "CandidateUpstreamClaimResult",
    "ChangedFile",
    "CrossedReleaseIndexEvidence",
    "CrossedReleaseIndexSelectionProblem",
    "CrossedReleaseIndexSelectionResult",
    "DEPENDENCY_CHANGE_PROBLEM_CODES",
    "DependencyChangeAnalysis",
    "DependencyChangeAnalysisResult",
    "DependencyChangeComparisonResult",
    "DependencyChangeEvidenceProblem",
    "DependencyChangeExtractionResult",
    "DependencyChangeProblemCode",
    "DependencyChangeResult",
    "DependencyCIExerciseResult",
    "DependencyCIExerciseState",
    "DependencyEvidenceMethod",
    "DependencyFileEvidence",
    "DependencyFileFormat",
    "DependencyReleaseInterval",
    "DependencyVersionChange",
    "DistributionFile",
    "ExtractedDependencyVersionChange",
    "FileProvenanceEvidence",
    "FileProvenanceProblem",
    "FileProvenanceResult",
    "GitHubAcquisitionError",
    "GitHubReadClient",
    "GitHubReleaseClient",
    "GitHubReleaseEvidence",
    "GitHubReleaseProblem",
    "GitHubReleaseResult",
    "GitHubResponseError",
    "GitHubTagCommitClient",
    "GitHubTagCommitEvidence",
    "GitHubTagCommitProblem",
    "GitHubTagCommitResult",
    "GroundedPythonSupportDropClaim",
    "GroundedUpstreamClaimSource",
    "IntervalGitHubReleaseSource",
    "OrderedCrossedReleaseVersions",
    "PackageMetadataCorroboration",
    "PackageReleaseEvidence",
    "PackageReleaseIndexEvidence",
    "PackageReleaseIndexProblem",
    "PackageReleaseIndexResult",
    "PackageReleaseProblem",
    "PackageReleaseResult",
    "PackagingVersionProblem",
    "ParsedDependencyReleaseInterval",
    "PinnedDependencyChange",
    "ProjectUrlCandidate",
    "PublisherIdentity",
    "PullRequestIdentity",
    "PyPIProvenanceClient",
    "PyPIReleaseClient",
    "PyPIReleaseIndexClient",
    "PythonLineSpecifierEvaluation",
    "PythonLineSpecifierProblem",
    "SelectedCrossedReleaseIndex",
    "TaggedChangelogEvidence",
    "TargetPythonRelevanceResult",
    "TargetPythonRelevanceState",
    "UPSTREAM_SOURCE_AUTHORITY_ORDER",
    "UnsupportedDependencyChange",
    "UpgradePilotInputError",
    "UpstreamAuthoritySourceProblem",
    "UpstreamIntervalAuthorityProblem",
    "UpstreamIntervalAuthorityResult",
    "UpstreamReleaseEvidence",
    "UpstreamSourceProblem",
    "UpstreamSourceResolver",
    "UpstreamSourceResult",
    "UpstreamSupportDropClaimProblem",
    "UpstreamSupportDropClaimResult",
    "WorkflowDependencyExerciseInput",
    "WorkflowDependencyExerciseResult",
    "analyze_dependency_change",
    "assemble_upstream_interval_authority",
    "compare_extracted_dependency_changes",
    "evaluate_dependency_ci_exercise",
    "evaluate_python_line_specifier",
    "evaluate_target_python_relevance",
    "extract_exact_requirement_changes",
    "extract_pinned_dependency_change",
    "extract_uv_lock_changes",
    "is_admitted_requirements_file",
    "is_exact_requirement_file",
    "is_modified_uv_lock_file",
    "is_uv_lock_file",
    "normalize_package_name",
    "normalize_project_url_label",
    "order_crossed_release_versions",
    "parse_dependency_release_interval",
    "release_interval_from_dependency_change",
    "select_crossed_release_index",
    "upstream_source_role",
    "validate_support_drop_candidates",
)
